GET https://www.nixmoney.com/history?ACCOUNTID=v.godzevich@interkassa.com&PASSPHRASE=nixmoney&ENDYEAR=2018
Accept: */*
Cache-Control: no-cache

###

GET https://www.nixmoney.com/resolve?ACCOUNTID=v.godzevich@interkassa.com&PASSPHRASE=nixmoney&RESOLVE=v.godzevich@interkassa.com&TYPE=USD
Accept: */*
Cache-Control: no-cache

###

GET https://www.liqpay.com/api/pay
Accept: */*
Cache-Control: no-cache

###

GET https://api.interkassa.com/v1/paysystem-input-payway
Accept: */*
Cache-Control: no-cache

###
GET https://api.interkassa.com/v1/currency
Accept: */*
Cache-Control: no-cache

###